#!/bin/bash

# raise an error if any command fails!
set -e

# existence of this file indicates that all dependencies were previously installed, and any changes to this file will use a different filename.
INITIALIZATION_FILE="$ANDROID_HOME/.initialized-dependencies-$(git log -n 1 --format=%h -- $0)"

if [ ! -e ${INITIALIZATION_FILE} ]; then
  echo "Fetch and initialize $ANDROID_HOME"

  command download-android 2 > /dev/null || ./download-android.sh

  echo -n "Use the final android sdk tools..."
  echo y | android update sdk --no-ui --filter platform-tool
  echo y | android update sdk --no-ui --filter tool > /dev/null
  echo "done."

  echo -n "Update build tools to 24..."
  echo y | android update sdk --no-ui --filter build-tools-24.0.2 --all > /dev/null
  echo "done."

  echo -n "Update SDK to 23..."
  echo y | android update sdk --no-ui --filter android-23 > /dev/null
  echo "done."

  # uncomment to install the Extra/Android Support Library
  # echo y | android update sdk --no-ui --filter extra-android-support --all > /dev/null

  echo -n "Install repositories..."
  # uncomment these if you are using maven/gradle to build your android project
  echo y | android update sdk --no-ui --filter extra-google-m2repository --all > /dev/null
  echo y | android update sdk --no-ui --filter extra-android-m2repository --all > /dev/null
  echo "done."

  echo -n "Install emulator..."
  # Specify at least one system image if you want to run emulator tests
  echo y | android update sdk --no-ui --filter sys-img-armeabi-v7a-android-23 --all > /dev/null
  echo "done."

  touch ${INITIALIZATION_FILE}
fi

#!/bin/bash
# This file was generated by chef, any changes will be lost!

set -e

ANDROID_SDK_URL="http://dl.google.com/android/android-sdk_r24.3.3-linux.tgz"
ANDROID_SDK_TAR="android-sdk_r24.3.3-linux.tgz"
ANDROID_TAR_PATH="${SNAP_CACHE_DIR}/downloads/${ANDROID_SDK_TAR}"
TEST_FILE=${ANDROID_HOME}/.snap-initialization

if [ ! -e "${TEST_FILE}" ]; then
  mkdir -p ${ANDROID_HOME}
  mkdir -p $(dirname $ANDROID_TAR_PATH)
  echo "Downloading android sdk from ${ANDROID_SDK_URL}"
  wget --quiet http://dl.google.com/android/android-sdk_r24.3.3-linux.tgz -O ${ANDROID_TAR_PATH}
  echo "Verifying integrity of downloaded file."
  (sha1sum ${ANDROID_TAR_PATH} | grep --silent --word-regexp cd4cab76c2e3d926b3495c26ec56c831ba77d0d0) || (echo "Could not verify integrity of android sdk, please try again"; exit 1)
  echo "Unpacking android sdk to \$ANDROID_HOME"
  tar -zxf ${ANDROID_TAR_PATH} -C ${ANDROID_HOME} --strip-components=1
  echo "Done. Android SDK is now available in \$ANDROID_HOME($ANDROID_HOME)"
  touch ${TEST_FILE}
else
  echo "Android SDK is already downloaded and installed in \$ANDROID_HOME($ANDROID_HOME)"
fi